#ifndef CUSTOM_DEFERREDPARAMS_INCLUDED  
#define CUSTOM_DEFERREDPARAMS_INCLUDED

#define MAX_LIGHT_COUNT_PER_TILE 32

#define MAX_LIGHT_COUNT 256
#define THREAD_NUM_X 16
#define THREAD_NUM_Y 16
#define THREAD_COUNT 256

#endif